### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Saif8599** [fatihg61/FDND-TEAM-LEAD#1]
Een aantal issues waar hij mij heeft geholpen.
- Het gebruiken en toepassen van geanimeerde bubbles als achtergrond voor onze squad page
- Uitgelegd over github branches 
- Noteer wijze van je wiki's

**Comment by fatihg61** [comment]
Ik heb Saif de basis dingen uitgelegd omtrent Github zo dat hij lekker makkelijk kan meedoen en wat CSS voorbeelden laten zien voor ze opdracht
