### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Zortux** [fatihg61/FDND-TEAM-LEAD#3]
hij heeft me geholpen met media queries en met responsive header design. Dankzij Fatih begrijp ik het nu. Dankjewel Fatih.

**Comment by fatihg61** [comment]
Mohammed had in het begin van zijn opleiding in vergelijking met ze medestudenten problemen met mobile design. Ik had hem toen het verhaal achter responsieve design geleerd op een begrijpelijke manier voor iemand die geen IT kennis heeft. Achter af had hij het verhaal begrepen en kon hij doormiddel van wat voorbeelden Media queries toepassen.
