### ISSUE TITLE
geholpen met merge conflict

### ISSUE THREAD

**Issue by KaanKalmi** [fatihg61/FDND-TEAM-LEAD#5]
Ik ben geholpen door Fatih  met merge conflicts oplossen in The Living Styleguide, hierbij was de site volledig kapot, met o.a missing sections, verplaatste sections naar example code etc.

**Comment by fatihg61** [comment]
Ik kon mij ook hier in terug vinden. Groepje van Kaan had hier problemen mee net voor het opleveren van hun opdracht. Ik had hun toen laten zien hoe je oude versies van je repo kan terugvinden waardoor je kan terugkeren naar een punt waar alles nog goed ging. Heb ze ook gezegd dat als je in branches werkt ook iedereen letterlijk ze eigen branch moet gebruiken wegens dat je anders weer dit kan meemaken.
