### ISSUE TITLE
Uitleg van hoe je een site maakt met HTML en CSS

### ISSUE THREAD

**Issue by KaanKalmi** [fatihg61/FDND-TEAM-LEAD#6]
Ik heb van fatih uitleg gekregen over hoe je het beste een site kan coderen met html, css. 

Hierbij had fatih live gecodeert en had hij de volgende site gemaakt:

![image](https://github.com/fatihg61/your-tribe-for-life-team-lead/assets/144000125/b22f360c-d620-4917-93d7-d40470d108fb)

Ik heb hieruit veel geleerd zoals, het gebruik van pure CSS om een pagina te bouwen. Ook kreeg ik een crash course over custom properties en heb ik ook geleerd hoe je een hamburger menu maakt zonder JS.

*edit* Ook hebben we een intro gekregen naar progressive enhancement! en kreeg ik ook ff te horen wat svelte was!

**Comment by Pink-Mallow** [comment]
Fatih heeft mij live stap voor stap simpel uitgelegd hoe html en Css samenwerken. Hij legde uit wat de basis opbouw is van html en hoe je het verder kan verwerken in css. Bijvoorbeeld met het menu:

![image](https://github.com/fatihg61/your-tribe-for-life-team-lead/assets/144671961/f4e7320d-cfe8-4ac3-bc68-07b866e65b7f)

Hij heeft gewerkt met de code &lt;ul>&lt;li>&lt;/li>&lt;/ul> en heeft duidelijk laten zien wat het verschil is tussen ul en il en wat je ermee kan in css.

Hij heeft dat ook laten zien met andere codes en geadviseerd om ermee te experimenteren om zelf te kunnen begrijpen hoe het werkt.

**Comment by fatihg61** [comment]
Ik heb voor Inez, Kaan en Ilona een crashcourse gegeven over hoe makkelijk je een pagina kan bouwen mits je de basis omarmt die we leren van de opleiding. Ik heb ze uitgelegd hoe je werkt met semantische html en hoe je een responsieve hamburger menu kan bouwen zonder CSS! Inez had wat meer uitleg nodig wegens dat ze achterliep met de opleiding maar wat meer aandacht geven en door open een andere tempo te gaan begreep ze het langzamerhand en toevallig is ze ook verder gegaan met Pure CSS!

**Comment by KrijnHoetmer** [comment]
Kijken jullie ook even naar https://codepen.io/krijnhoetmer/pen/GRzLWmW — heeft Fatih dit ook zo uitgelegd? ;)
